# GENERATE TIME: Fri Mar  1 17:58:26 2024
# CMD:
# .\basicsr\train.py -opt .\options\train\EDSR\train_EDSR_Lx3.yml

# general settings
name: EDSR_CADRotated_wFlaws_REC_FDK_145_Views_shortANDsparse_Lx3_NOnoise_NOblur
model_type: SRModel
scale: 3
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: CADRotated_wFlaws_REC_FDK_145_Views_shortANDsparse_X3
    type: PairedImageDataset
    dataroot_gt: S:\NAOA\Projects\AM-SuperResolution\datasets\noBH\Al\CADRotated_wFlaws_REC_FDK_145_Views_shortANDsparse\X3\GT_sub_120\train
    dataroot_lq: S:\NAOA\Projects\AM-SuperResolution\datasets\noBH\Al\CADRotated_wFlaws_REC_FDK_145_Views_shortANDsparse\X3\LR_NOnoise_NOblur_sub_40\train
    # (for lmdb
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X3_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 120
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 16
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: CADRotated_wFlaws_REC_FDK_145_Views_shortANDsparse
    type: PairedImageDataset
    dataroot_gt: S:\NAOA\Projects\AM-SuperResolution\datasets\noBH\Al\CADRotated_wFlaws_REC_FDK_145_Views_shortANDsparse\X3\GT_sub_120\val
    dataroot_lq: S:\NAOA\Projects\AM-SuperResolution\datasets\noBH\Al\CADRotated_wFlaws_REC_FDK_145_Views_shortANDsparse\X3\LR_NOnoise_NOblur_sub_40\val
    io_backend:
      type: disk

# network structures
network_g:
  type: EDSR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 256
  num_block: 32
  upscale: 3
  res_scale: 0.1
  img_range: 255.
  rgb_mean: [0.0, 0.0, 0.0]

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e2
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 3
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
